"""initial schema

Revision ID: 96e188c70d73
Revises: 
Create Date: 2026-05-04 17:21:05.870250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '96e188c70d73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('weekly_balance_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('earliest_start', sa.Time(), nullable=False),
    sa.Column('latest_end', sa.Time(), nullable=False),
    sa.Column('study_block_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wellness_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_sleep_hours_per_day', sa.Float(), nullable=False),
    sa.Column('workouts_per_week', sa.Integer(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('self_care_blocks_per_week', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_blocks')
    op.drop_table('wellness_goals')
    op.drop_table('tasks')
    op.drop_table('preferences')
    op.drop_table('plans')
    op.drop_table('events')
    # ### end Alembic commands ###